### ISSUE TITLE
more robustly check for disk-only or bulge-only galaxies

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/sims_GCRCatSimInterface#10]
Right now we use the SED to check if the galaxy has only disk or only bulge (see [`python/desc/sims/GCRCatSimInterface/CatalogClasses.py#L27`](https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/master/python/desc/sims/GCRCatSimInterface/CatalogClasses.py#L27)). 

I think the suggestion from @dkorytov is to use the disk/bulge size.

This should be a straightforward change too and I am also happy to take on it. @danielsf, comments or thoughts?

**Comment by jchiang87** [comment]
Feel free to work on this stuff, but unless it is absolutely essential to get Run1.1p going, it won't be part of the release for that run.

**Comment by yymao** [comment]
@jchiang87 I don't think any of #8, #9, and #10 are critical for Run 1.1p, they are mostly just to reduce future confusion...

**Comment by dkorytov** [comment]
I think the best value to use is stellar mass. If any component has zero stellar mass, I zero out all luminosities. Now that I think about it, a zero stellar mass object might still have a non-zero radius as I don't zero that out.

**Comment by danielsf** [comment]
Stellar mass sounds good to me.
