### ISSUE TITLE
use 'protoDC2' instead of 'proto-dc2_v2.1.2'

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/sims_GCRCatSimInterface#18]
When getting the catalog from `GCRCatalogs`, it would be better to use `'protoDC2'` instead of `'proto-dc2_v2.1.2'`, so that when `'proto-dc2_v2.1.2'`become obsolete in a future version of `GCRCatalogs`, this interface will also receive the same update. 

Note that, when using a frozen version of `GCRCatalogs`, `'protoDC2'` will *always* point to the same catalog, even if the upstream has updates (it'll only print out a warning message). So there is no need to worry about catalog version not being controlled when using `'protoDC2'`, as it only updates with the `GCRCatalogs` package. 

Here's the current occurrence of `'proto-dc2_v2.1.2'` in master:
```
workspace/compound_db/verify_compound_catalog.py
13:    yaml_file_name = 'proto-dc2_v2.1.2'

workspace/compound_db/make_compound_catalog.py
11:    yaml_file_name = 'proto-dc2_v2.1.2'

tests/test_full_instanceCatalogs.py
40:        db = diskDESCQAObject_protoDC2(yaml_file_name='proto-dc2_v2.1.2')
66:        db = diskDESCQAObject_protoDC2(yaml_file_name='proto-dc2_v2.1.2')

bin.src/create_agn_db.py
86:                        default='proto-dc2_v2.1.2',
88:                        "Default = 'proto-dc2_v2.1.2'")

workspace/agn_params/test_phosim_agn_catalog.py
13:    db = agnDESCQAObject_protoDC2(yaml_file_name='proto-dc2_v2.1.2')

workspace/agn_params/test_agn_catalog.py
22:    db = agnDESCQAObject_protoDC2(yaml_file_name='proto-dc2_v2.1.2')

workspace/agn_params/test_agn_compound.py
18:    yaml_file_name = 'proto-dc2_v2.1.2'
```

**Comment by jchiang87** [comment]
Thanks, @yymao .  I noticed this also.  I think the only absolutely crucial one to change is the `create_agn_db.py` case, since the others are for test code and/or scaffolding, but it would be best to change all of them.
