### ISSUE TITLE
Confirm that warning messages should be ignored

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/sims_GCRCatSimInterface#23]
I am encountering a number of warning messages in running @jchiang87 's script that I don't think I have been seeing in catsim before. This suggests that we are trying to read in dust parameters , being passed as `np.nan` and while it certainly does not crash the code, I was wondering if this might lead to certain objects getting excluded from catalogs. I am guessing @danielsf knows the code producing this.  Can we please confirm that this worry is unfounded.
```
/global/homes/r/rbiswas/src/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/CatalogClasses.py:129: RuntimeWarning: divide by zero encountered in log10
  av_list = -2.5*(np.log10(self.column_by_name(v_dust_name)) -
/global/homes/r/rbiswas/src/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/CatalogClasses.py:134: RuntimeWarning: divide by zero encountered in log10
  np.log10(self.column_by_name(b_name)) +
/global/homes/r/rbiswas/src/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/CatalogClasses.py:134: RuntimeWarning: invalid value encountered in subtract
  np.log10(self.column_by_name(b_name)) +
/global/homes/r/rbiswas/src/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/CatalogClasses.py:137: RuntimeWarning: divide by zero encountered in true_divide
  rv_list = av_list/ebv_list
/global/homes/r/rbiswas/src/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/CatalogClasses.py:137: RuntimeWarning: invalid value encountered in true_divide
  rv_list = av_list/ebv_list
/global/homes/r/rbiswas/src/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/CatalogClasses.py:149: RuntimeWarning: invalid value encountered in less
  np.logical_or(rv_list<1.0, rv_list>5.0)))
/global/homes/r/rbiswas/src/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/CatalogClasses.py:149: RuntimeWarning: invalid value encountered in greater
  np.logical_or(rv_list<1.0, rv_list>5.0)))
```

**Comment by jchiang87** [comment]
These have been present at least since we have been using the protoDC2 catalog for the galaxies.  I've run that script scores of times and haven't run into any problems operationally.

**Comment by danielsf** [comment]
We calculate dust parameters by taking fluxes in the B and V bands for the bulge and disk components, converting them to magnitudes, and then subtracting them.  These errors arise when galaxies don't actually have flux in a given band for a given component.  Such galaxies are ultimately weeded out by the `cannot_be_null=[hasBulge]` and `cannot_be_null=[hasDisk]` attributes of the corresponding InstanceCatalogs.

**Comment by rbiswas4** [comment]
Good, so this is not a problem :). Closing issue now.
