### ISSUE TITLE
Configuration and running of generateInstanceCat.py

### ISSUE THREAD

**Issue by TomGlanzman** [LSSTDESC/sims_GCRCatSimInterface#25]
I am integrating the new instanceCat generation in to the DC2-phoSim workflow at NERSC and have cobbled together hints from various people on how to set up and run the script.  What I have does not quite work yet (possibly because there continues to be ongoing work in this repo).  In any event, here is my current flawed recipe.

```
source /global/common/software/lsst/cori-haswell-gcc/stack/setup_w_2017_46_py3_gcc6.sh
setup lsst_sims
eups declare gcr_catalogs -r /global/projecta/projectdirs/lsst/production/DC2/gcr-catalogs -c
setup gcr_catalogs
source /global/projecta/projectdirs/lsst/production/DC2/sims_GCRCatSimInterface/setup/setup.sh
```
All three of DC2_Repo, gcr-catalogs and sims_GCRCatSimInterface are running the current master branch.  (Yes, at some point soon, will need tags.)

Then to run the code:

```
/usr/bin/time python /global/projecta/projectdirs/lsst/production/DC2/sims_GCRCatSimInterface/bin.src/generateInstCat.py --db /global/projecta/projectdirs/lsst/groups/SSim/DC2/minion_1016_desc_dithered_v4.db --agn_db_name /global/cscratch1/sd/jchiang8/DC2_prs/agn_db_mbh_7.0_m_i_30.0.sqlite --descqa_catalog protoDC2 -- fov 0.5 --protoDC2_ra 55.064 --protoDC2_dec -29.783 --enable_sprinkler --out_dir /global/cscratch1/sd/descpho/Pipeline-tasks/DC2-phoSim-3_WFD-r/000001/instCat
```
This generates the following output:
```Traceback (most recent call last):
  File "/global/projecta/projectdirs/lsst/production/DC2/sims_GCRCatSimInterface/bin.src/generateInstCat.py", line 3, in 
    from desc.sims.GCRCatSimInterface import *
  File "/global/projecta/projectdirs/lsst/production/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/__init__.py", line 9, in 
    from .TwinklesClasses import *
  File "/global/projecta/projectdirs/lsst/production/DC2/sims_GCRCatSimInterface/python/desc/sims/GCRCatSimInterface/TwinklesClasses.py", line 3, in 
    from desc.twinkles.twinklesVariabilityMixins import VariabilityTwinkles
ModuleNotFoundError: No module named 'desc.twinkles'
```

Am I missing something in the setup or should I just be patient for the dust to settle in the ongoing work?

One last request/hint: the generateInstCat.py makes nice use of argparse.  If the ```from desc.sims.GCRCatSimInterface import *``` line could be placed *after* ```args = parser.parse_args()``` then one could issue the command ```generateInstCat.py -h``` for some useful info (rather than a crash)!

**Comment by jchiang87** [comment]
You need to wait for the dust to settle on the development.  Also you don't need to prepend `python` before `generateInstCat.py`.  It is an executable.

**Comment by TomGlanzman** [comment]
Dust has settled
