### ISSUE TITLE
Random dust extinction for offensive catalog entries

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/sims_GCRCatSimInterface#5]
@jchiang87 @danielsf  While running tests for https://github.com/LSSTDESC/sims_GCRCatSimInterface/pull/2 I came across an issue where a small number of galaxies were suddenly much brighter when the knots component was included compared to the baseline. After some digging, it turned out that the internal dust parameters were different for these objects between the instance catalogs produced with and without random walk.
Here is an example where you can see a source popping up on the right image which is generated with a RandomWalk component:
![image](https://user-images.githubusercontent.com/861591/35361684-4723bb32-0130-11e8-8d8f-0e093a01985e.png) ![image](https://user-images.githubusercontent.com/861591/35361692-54dc15a8-0130-11e8-8aa0-ab8cbab1f464.png)

What is going on is that for some objects in the protoDC2 catalog, the internal dust parameter computation fails, in which case they are replaced by some random values:
https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/32fe5d7cd3bb63e41623de486e841194dd2a8346/python/desc/sims/GCRCatSimInterface/CatalogClasses.py#L75

The random number generator is seeded in the code, so that running the instance catalog generation twice gives the same answer, but if you remove some disk components (which happens when the RandomWalk component uses all of the flux in the disk) then the random sequence that sets the offensive dust parameters will be different, leading to potentially quite different results. 

One easy fix in my code would be to never actually set the disk flux to 0 but to some non-zero epsilon value. But the fact that I could see this effect by eye in noisy images coupled with the fact that there is no warning or error message associated to it worries me a bit. Wouldn't it make more sense to request from descqa that the dust parameters are reasonable in the protoDC2 catalog ?

**Comment by danielsf** [comment]
The ANL team is aware of the bad dust values in protoDC2.  I believe that the plan is to have this fixed in the final DC2 catalog.  I think the fix was too much work to justify doing "only" for protoDC2.

**Comment by EiffL** [comment]
Ok, great :-) so I guess I'll just go for an easy fix that preserves the random sequence

**Comment by yymao** [comment]
Just so that people can find relevant information: https://github.com/LSSTDESC/gcr-catalogs/issues/70

**Comment by EiffL** [comment]
Ok, done. I now preserve the number of disk components even if some of them have very small fluxes, this makes the two instance catalogs with and without knots consistent. As @yymao pointed out the dust parameters are on track to be included in the reader anyway and this will no longer be an issue.
