### ISSUE TITLE
update SED labels to conform to GCR schema

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/sims_GCRCatSimInterface#8]
While this can be as simple as just replace the content in the `data/dc2_seds.txt`, I feel like we can use this chance to refactor the first part of `data/get_sed_mags.py`: instead of getting the SED labels from a text file, we can directly obtain them from GCR directly.

@danielsf any comments or suggestions? I'll be happy to take a stab on this.

**Comment by danielsf** [comment]
If you can get them directly from the GCR, I support it.
